/**
 * Drupal Simple XML Sitemap–flavoured client-side XSL stylesheet
 * for the drupal-bartik theme's `/sitemap.xml` and sub-sitemaps.
 * Kept as a plain TS module (rather than a `.xsl` file imported via
 * Vite's `?raw`) so it works uniformly under Vite (dev + build) and
 * the Node test runner.
 */
export default `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>XML Sitemap</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="robots" content="noindex,follow"/>
    <style type="text/css">
        body { font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #333; background: #fff; margin: 0; padding: 0; }
        #wrapper { max-width: 980px; margin: 0 auto; padding: 30px 20px; }
        h1 { font-size: 26px; color: #0074bd; margin: 0 0 0.25em; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }
        p { line-height: 1.4; }
        p.intro { color: #555; }
        a { color: #0071b3; text-decoration: none; }
        a:hover { text-decoration: underline; }
        table { width: 100%; border-collapse: collapse; margin-top: 1em; }
        thead th { text-align: left; padding: 8px 10px; background: #f3f4f5; border-bottom: 1px solid #ccc; font-weight: bold; color: #444; }
        tbody td { padding: 6px 10px; border-bottom: 1px solid #eee; vertical-align: top; }
        tbody tr:hover td { background: #fafafa; }
        .footnote { margin-top: 2em; font-size: 12px; color: #888; }
    </style>
</head>
<body>
    <div id="wrapper">
        <h1>XML Sitemap</h1>
        <p class="intro">This sitemap is generated by the <a href="https://www.drupal.org/project/simple_sitemap">Simple XML Sitemap</a> module for Drupal. It is intended for search engine crawlers.</p>
        <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <p>Sitemap index with <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sub-sitemaps.</p>
            <table>
                <thead>
                    <tr>
                        <th>Sitemap</th>
                        <th>Last changed</th>
                    </tr>
                </thead>
                <tbody>
                    <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                        <tr>
                            <td>
                                <xsl:variable name="sitemapURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
                                <a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
                            </td>
                            <td><xsl:value-of select="sitemap:lastmod"/></td>
                        </tr>
                    </xsl:for-each>
                </tbody>
            </table>
        </xsl:if>
        <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <p>Listing <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.</p>
            <table>
                <thead>
                    <tr>
                        <th>URL</th>
                        <th>Last changed</th>
                    </tr>
                </thead>
                <tbody>
                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                        <tr>
                            <td>
                                <xsl:variable name="itemURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
                                <a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
                            </td>
                            <td><xsl:value-of select="sitemap:lastmod"/></td>
                        </tr>
                    </xsl:for-each>
                </tbody>
            </table>
        </xsl:if>
        <p class="footnote">Generated by the <a href="https://www.drupal.org/project/simple_sitemap">Simple XML Sitemap</a> Drupal module.</p>
    </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
`;
