/**
 * Yoast SEO–flavoured client-side XSL stylesheet for the wp-classic
 * theme's `/sitemap.xml` and sub-sitemaps. Kept as a plain TS module
 * (rather than a `.xsl` file imported via Vite's `?raw`) so it works
 * uniformly under Vite (dev + build) and the Node test runner.
 */
export default `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>XML Sitemap</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="robots" content="noindex,follow"/>
    <style type="text/css">
        body { font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #545353; margin: 0; padding: 0; }
        #content { margin: 0 auto; width: 1000px; }
        a { color: #000; text-decoration: none; }
        a:hover { text-decoration: underline; }
        h1 { font-size: 2em; margin-bottom: 0; }
        p { font-size: 1em; }
        p.expl { margin-bottom: 1em; }
        p.expl a { color: #da3114; font-weight: bold; }
        table { border: none; border-collapse: collapse; width: 100%; }
        th { text-align: left; padding: 5px 15px 5px 5px; font-size: 11px; }
        thead th { background-color: #4275f4; color: white; cursor: pointer; }
        tr.high { background-color: #e7feff; }
        tbody tr:nth-child(odd) td { background-color: #f7f7f7; }
        td { padding: 5px 15px 5px 5px; font-size: 11px; }
        #footer { margin: 1em auto; font-size: 0.85em; text-align: center; }
    </style>
</head>
<body>
    <div id="content">
        <h1>XML Sitemap</h1>
        <p class="expl">This XML Sitemap is generated by <a href="https://yoast.com/wordpress/plugins/seo/">Yoast SEO</a>. It is what search engines use to crawl and re-crawl posts/pages/products/etc on your site.</p>
        <p class="expl">More information about XML sitemaps can be found at <a href="https://www.sitemaps.org">sitemaps.org</a>.</p>
        <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <p class="expl">This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.</p>
            <table id="sitemap">
                <thead>
                    <tr>
                        <th width="75%">Sitemap</th>
                        <th width="25%">Last Modified</th>
                    </tr>
                </thead>
                <tbody>
                    <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                        <tr>
                            <td>
                                <xsl:variable name="sitemapURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
                                <a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
                            </td>
                            <td><xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/></td>
                        </tr>
                    </xsl:for-each>
                </tbody>
            </table>
        </xsl:if>
        <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <p class="expl">This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
            <table id="sitemap">
                <thead>
                    <tr>
                        <th width="75%">URL</th>
                        <th width="25%">Last Modified</th>
                    </tr>
                </thead>
                <tbody>
                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                        <tr>
                            <td>
                                <xsl:variable name="itemURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
                                <a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
                            </td>
                            <td><xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/></td>
                        </tr>
                    </xsl:for-each>
                </tbody>
            </table>
        </xsl:if>
        <div id="footer"><p>Generated by <a href="https://yoast.com/wordpress/plugins/seo/">Yoast SEO</a></p></div>
    </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
`;
